export default {
    SET_CURRENT_USER:'SET_CURRENT_USER',
    SET_CREATE_PROJECT_IMG:'SET_CREATE_PROJECT_IMG',
    DEL_CREATE_PROJECT_IMG:'DEL_CREATE_PROJECT_IMG',
    SET_CREATE_PROJECT_MEMBER:'SET_CREATE_PROJECT_MEMBER',
    DEL_CREATE_PROJECT_MEMBER:'DEL_CREATE_PROJECT_MEMBER',
}